const { Division, Year } = require('../database');

/**
 * Get all divisions
 */
exports.getAllDivisions = async (req, res) => {
  try {
    const { yearId } = req.query;
    const query = {};
    if (yearId) query.year = yearId;

    const divisions = await Division.find(query).populate('year');
    res.status(200).json({
      message: 'Divisions retrieved successfully',
      divisions
    });
  } catch (error) {
    console.error('Error retrieving divisions:', error);
    res.status(500).json({
      message: 'Error retrieving divisions',
      error: error.message
    });
  }
};

/**
 * Get a specific division
 */
exports.getDivision = async (req, res) => {
  try {
    const { id } = req.params;
    const division = await Division.findById(id).populate('year');

    if (!division) {
      return res.status(404).json({ message: 'Division not found' });
    }

    res.status(200).json({
      message: 'Division retrieved successfully',
      division
    });
  } catch (error) {
    console.error('Error retrieving division:', error);
    res.status(500).json({
      message: 'Error retrieving division',
      error: error.message
    });
  }
};

/**
 * Create a new division
 */
exports.createDivision = async (req, res) => {
  try {
    const { name, year, capacity } = req.body;

    // Validate input
    if (!name || !year) {
      return res.status(400).json({ message: 'Name and year are required' });
    }

    // Validate name is A or B
    if (!['A', 'B', 'C', 'D'].includes(name)) {
      return res.status(400).json({ message: 'Division name must be A, B, C, or D' });
    }

    const division = new Division({
      name,
      year,
      displayName: `${name} Division`,
      capacity: capacity || 60
    });

    await division.save();
    await division.populate('year');

    res.status(201).json({
      message: 'Division created successfully',
      division
    });
  } catch (error) {
    console.error('Error creating division:', error);
    res.status(500).json({
      message: 'Error creating division',
      error: error.message
    });
  }
};

/**
 * Update a division
 */
exports.updateDivision = async (req, res) => {
  try {
    const { id } = req.params;
    const { name, capacity } = req.body;

    const division = await Division.findByIdAndUpdate(
      id,
      {
        name: name || undefined,
        displayName: name ? `${name} Division` : undefined,
        capacity: capacity || undefined,
        updated_at: new Date()
      },
      { new: true }
    ).populate('year');

    if (!division) {
      return res.status(404).json({ message: 'Division not found' });
    }

    res.status(200).json({
      message: 'Division updated successfully',
      division
    });
  } catch (error) {
    console.error('Error updating division:', error);
    res.status(500).json({
      message: 'Error updating division',
      error: error.message
    });
  }
};

/**
 * Delete a division
 */
exports.deleteDivision = async (req, res) => {
  try {
    const { id } = req.params;
    const division = await Division.findByIdAndDelete(id);

    if (!division) {
      return res.status(404).json({ message: 'Division not found' });
    }

    res.status(200).json({
      message: 'Division deleted successfully'
    });
  } catch (error) {
    console.error('Error deleting division:', error);
    res.status(500).json({
      message: 'Error deleting division',
      error: error.message
    });
  }
};

/**
 * Auto-generate divisions (A, B) for a year
 */
exports.autoGenerateDivisions = async (req, res) => {
  try {
    const { yearId } = req.body;

    if (!yearId) {
      return res.status(400).json({ message: 'Year ID is required' });
    }

    const year = await Year.findById(yearId);
    if (!year) {
      return res.status(404).json({ message: 'Year not found' });
    }

    // Check if divisions already exist
    const existingDivisions = await Division.find({ year: yearId });
    if (existingDivisions.length > 0) {
      return res.status(400).json({ 
        message: 'Divisions already exist for this year',
        divisions: existingDivisions
      });
    }

    // Create standard divisions
    const divisionsToCreate = [
      { name: 'A', year: yearId, displayName: 'A Division', capacity: 60 },
      { name: 'B', year: yearId, displayName: 'B Division', capacity: 60 }
    ];

    const createdDivisions = await Division.insertMany(divisionsToCreate);
    await Division.populate(createdDivisions, { path: 'year' });

    res.status(201).json({
      message: `Successfully created ${createdDivisions.length} divisions`,
      count: createdDivisions.length,
      divisions: createdDivisions
    });
  } catch (error) {
    console.error('Error auto-generating divisions:', error);
    res.status(500).json({
      message: 'Error generating divisions',
      error: error.message
    });
  }
};
