services:
  nginx:
    image: nginx:alpine
    container_name: nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      

    depends_on:
      - frontend
      - backend

    restart: unless-stopped
  mongo:
    image: mongo:8.0
    container_name: mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

    restart: unless-stopped


  backend:
    build: ./backend

    command: npm run dev

    container_name: backend

    env_file:
      - .env_backend

    volumes:
      - ./backend:/app

    ports:
      - "5001:5001"

    depends_on:
      - mongo

    restart: unless-stopped


  frontend:
    build: ./frontend

    container_name: frontend

    env_file:
      - .env  # ya .env agar wahi use kar rahe ho

    

    ports:
      - "3000:3000"

    depends_on:
      - backend

    restart: unless-stopped


volumes:
  mongo-data: