const express = require('express');
const router = express.Router();
const divisionController = require('../controllers/divisionController');

/**
 * @route POST /api/division/auto-generate
 * @desc Auto-generate standard divisions (A, B) for a year
 */
router.post('/auto-generate', divisionController.autoGenerateDivisions);

/**
 * @route GET /api/division
 * @desc Get all divisions
 */
router.get('/', divisionController.getAllDivisions);

/**
 * @route GET /api/division/:id
 * @desc Get a specific division
 */
router.get('/:id', divisionController.getDivision);

/**
 * @route POST /api/division
 * @desc Create a new division
 */
router.post('/', divisionController.createDivision);

/**
 * @route PUT /api/division/:id
 * @desc Update a division
 */
router.put('/:id', divisionController.updateDivision);

/**
 * @route DELETE /api/division/:id
 * @desc Delete a division
 */
router.delete('/:id', divisionController.deleteDivision);

module.exports = router;
