'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import axios from 'axios'
import Navbar from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5001'

export default function DivisionsPage() {
  const router = useRouter()
  const [facultyName, setFacultyName] = useState('')
  const [divisions, setDivisions] = useState([])
  const [years, setYears] = useState([])
  const [loading, setLoading] = useState(false)
  const [showForm, setShowForm] = useState(false)
  const [editingDivision, setEditingDivision] = useState(null)
  const [notification, setNotification] = useState({ type: '', message: '' })
  const [formData, setFormData] = useState({
    name: 'A',
    year: '',
    capacity: 60
  })

  useEffect(() => {
    const email = sessionStorage.getItem('facultyEmail')
    const name = sessionStorage.getItem('facultyName')
    if (!email) {
      router.push('/')
      return
    }
    setFacultyName(name || '')
    fetchDivisions()
    fetchYears()
  }, [router])

  const fetchDivisions = async () => {
    try {
      setLoading(true)
      const response = await axios.get(`${API_URL}/api/division`)
      setDivisions(response.data.divisions || [])
    } catch (error) {
      console.error('Error fetching divisions:', error)
      showNotification('error', 'Failed to load divisions')
    } finally {
      setLoading(false)
    }
  }

  const fetchYears = async () => {
    try {
      const response = await axios.get(`${API_URL}/api/year`)
      setYears(response.data.years || [])
    } catch (error) {
      console.error('Error fetching years:', error)
    }
  }

  const showNotification = (type, message) => {
    setNotification({ type, message })
    setTimeout(() => setNotification({ type: '', message: '' }), 3000)
  }

  const handleSave = async () => {
    if (!formData.name || !formData.year) {
      showNotification('error', 'Name and year are required')
      return
    }

    try {
      if (editingDivision) {
        await axios.put(`${API_URL}/api/division/${editingDivision._id}`, formData)
        showNotification('success', 'Division updated successfully')
      } else {
        await axios.post(`${API_URL}/api/division`, formData)
        showNotification('success', 'Division created successfully')
      }
      setShowForm(false)
      resetForm()
      fetchDivisions()
    } catch (error) {
      console.error('Error saving division:', error)
      showNotification('error', error.response?.data?.message || 'Failed to save division')
    }
  }

  const resetForm = () => {
    setFormData({
      name: 'A',
      year: '',
      capacity: 60
    })
  }

  const handleDelete = async (id) => {
    if (!confirm('Are you sure you want to delete this division?')) return

    try {
      await axios.delete(`${API_URL}/api/division/${id}`)
      showNotification('success', 'Division deleted successfully')
      fetchDivisions()
    } catch (error) {
      console.error('Error deleting division:', error)
      showNotification('error', 'Failed to delete division')
    }
  }

  const handleEdit = (division) => {
    setEditingDivision(division)
    setFormData({
      name: division.name,
      year: division.year._id,
      capacity: division.capacity || 60
    })
    setShowForm(true)
  }

  const handleAutoGenerateDivisions = async () => {
    const selectedYear = divisions.length > 0 && divisions[0].year ? divisions[0].year._id : years[0]?._id
    
    if (!selectedYear) {
      showNotification('error', 'Please create an academic year first')
      return
    }

    const confirmCreate = confirm(
      'This will create standard divisions (A, B) for the selected year.\n\nContinue?'
    )
    if (!confirmCreate) return

    try {
      const response = await axios.post(`${API_URL}/api/division/auto-generate`, {
        yearId: selectedYear
      })
      showNotification('success', `${response.data.count} divisions created successfully!`)
      fetchDivisions()
    } catch (error) {
      console.error('Error auto-generating divisions:', error)
      const errorMessage = error.response?.data?.message || 'Failed to create divisions'
      showNotification('error', errorMessage)
    }
  }

  const handleLogout = () => {
    sessionStorage.clear()
    router.push('/')
  }

  return (
    <div className="flex h-screen bg-gray-50">
      <Sidebar facultyName={facultyName} />
      <main className="flex-1 flex flex-col ml-64">
        <Navbar facultyName={facultyName} onLogout={handleLogout} />
        
        <div className="flex-1 overflow-auto pt-16">
          <div className="px-6 py-6 space-y-6">
            {/* Header */}
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-2xl font-bold text-gray-900">Divisions</h1>
                <p className="text-sm text-gray-500 mt-1">Manage student divisions and groups</p>
              </div>
              <div className="flex gap-3">
                <button
                  onClick={handleAutoGenerateDivisions}
                  className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-semibold rounded-lg transition-colors text-sm"
                >
                  Auto-Generate (A, B)
                </button>
                <button
                  onClick={() => {
                    setEditingDivision(null)
                    resetForm()
                    setShowForm(true)
                  }}
                  className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition-colors"
                >
                  + New Division
                </button>
              </div>
            </div>

            {/* Notification */}
            {notification.message && (
              <div
                className={`p-4 rounded-lg ${
                  notification.type === 'success'
                    ? 'bg-green-50 border border-green-200 text-green-800'
                    : 'bg-red-50 border border-red-200 text-red-800'
                }`}
              >
                <p className="font-medium">{notification.message}</p>
              </div>
            )}

            {/* Form Modal */}
            {showForm && (
              <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50 overflow-y-auto">
                <div className="bg-white border border-gray-200 rounded-lg p-8 max-w-md w-full my-8 shadow-lg">
                  <h2 className="text-xl font-bold text-gray-900 mb-6">
                    {editingDivision ? 'Edit Division' : 'New Division'}
                  </h2>

                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-semibold text-gray-900 mb-2">Division Name</label>
                      <select
                        value={formData.name}
                        onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                        className="w-full px-4 py-2 border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                      >
                        <option value="A">A</option>
                        <option value="B">B</option>
                        <option value="C">C</option>
                        <option value="D">D</option>
                      </select>
                    </div>

                    <div>
                      <label className="block text-sm font-semibold text-gray-900 mb-2">Year</label>
                      <select
                        value={formData.year}
                        onChange={(e) => setFormData({ ...formData, year: e.target.value })}
                        className="w-full px-4 py-2 border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                      >
                        <option value="">-- Select Year --</option>
                        {years.map((year) => (
                          <option key={year._id} value={year._id}>
                            {year.displayName}
                          </option>
                        ))}
                      </select>
                    </div>

                    <div>
                      <label className="block text-sm font-semibold text-gray-900 mb-2">Student Capacity</label>
                      <input
                        type="number"
                        min="1"
                        value={formData.capacity}
                        onChange={(e) => setFormData({ ...formData, capacity: parseInt(e.target.value) })}
                        className="w-full px-4 py-2 border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                      />
                    </div>
                  </div>

                  <div className="flex gap-3 mt-6">
                    <button
                      onClick={() => setShowForm(false)}
                      className="flex-1 px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-900 rounded-lg font-semibold transition-colors"
                    >
                      Cancel
                    </button>
                    <button
                      onClick={handleSave}
                      className="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-semibold transition-colors"
                    >
                      Save
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* Divisions Table */}
            <div className="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden">
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="bg-gradient-to-r from-blue-50 to-indigo-50 border-b border-gray-200">
                      <th className="px-6 py-3 text-left text-gray-900 font-semibold text-sm">Name</th>
                      <th className="px-6 py-3 text-left text-gray-900 font-semibold text-sm">Year</th>
                      <th className="px-6 py-3 text-left text-gray-900 font-semibold text-sm">Capacity</th>
                      <th className="px-6 py-3 text-left text-gray-900 font-semibold text-sm">Display Name</th>
                      <th className="px-6 py-3 text-left text-gray-900 font-semibold text-sm">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {divisions.map((division) => (
                      <tr key={division._id} className="border-b border-gray-200 hover:bg-gray-50 transition-colors">
                        <td className="px-6 py-3 text-gray-900 font-bold text-lg">{division.name}</td>
                        <td className="px-6 py-3 text-gray-600 text-sm">{division.year?.displayName}</td>
                        <td className="px-6 py-3 text-gray-600 text-sm">{division.capacity} students</td>
                        <td className="px-6 py-3 text-gray-600 text-sm">{division.displayName}</td>
                        <td className="px-6 py-3">
                          <div className="flex gap-2">
                            <button
                              onClick={() => handleEdit(division)}
                              className="px-3 py-1 bg-blue-600 hover:bg-blue-700 text-white text-sm rounded transition-colors"
                            >
                              Edit
                            </button>
                            <button
                              onClick={() => handleDelete(division._id)}
                              className="px-3 py-1 bg-red-50 hover:bg-red-100 text-red-600 text-sm rounded transition-colors border border-red-200"
                            >
                              Delete
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {loading ? (
                <div className="text-center py-8">
                  <p className="text-gray-500">Loading divisions...</p>
                </div>
              ) : divisions.length === 0 ? (
                <div className="text-center py-12">
                  <p className="text-gray-500">No divisions found. Create one to get started.</p>
                  <button
                    onClick={handleAutoGenerateDivisions}
                    className="mt-4 px-6 py-2 bg-green-600 hover:bg-green-700 text-white font-semibold rounded-lg transition-colors"
                  >
                    Auto-Generate Standard Divisions (A, B)
                  </button>
                </div>
              ) : null}
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
